FROM python:3.11 AS builder
WORKDIR /install
COPY requirement.txt .
RUN pip install --prefix=/install -r requirement.txt

FROM python:alpine
WORKDIR /app
COPY --from=builder /install /usr/local
COPY app.py .
EXPOSE 5000
CMD ["python", "app.py"]